version: 2.1

workflows:
  build-test:
    jobs:
      - prep-deps
      - test-build:
          requires:
            - prep-deps
      - test-lint:
          requires:
            - prep-deps
      - all-tests-pass:
          requires:
            - test-build
            - test-lint

jobs:
  prep-deps:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            .circleci/scripts/deps-install.sh
      - run:
          name: Collect yarn install HAR logs
          command: |
            .circleci/scripts/collect-har-artifact.sh
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build-artifacts

  test-build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn build

  test-lint:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

  all-tests-pass:
    docker:
      - image: circleci/node:16
    steps:
      - run:
          name: All tests passed
          command: echo 'Great success'
